name = "aci-worker"
main = "src/index.js"
compatibility_date = "2025-10-01"

# optional: custom domain binding if you set it in Cloudflare later
# routes = [{ pattern = "aci.aliasnet. workers.dev/*", custom_domain = true }]
