name = "aci"
main = "src/index.js"
compatibility_date = "2025-10-01"

# no workers_dev anymore since you’ll use your own domain
workers_dev = false

routes = [
  { pattern = "aci.aliasmail.cc/*", zone_id = "06cc7a57b0cb8c6926606ee05bc72e6d" }
]

[placement]
mode = "smart"

[observability.logs]
enabled = true
