name: Deploy Worker + ensure Secrets Store secrets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      STORE_ID: "9e0c080b325b413b80ee27ca929361fb"   # your Store ID (not secret)
      HMAC_KEY_VALUE: ${{ secrets.HMAC_KEY_VALUE }}
      ADMIN_KEY_VALUE: ${{ secrets.ADMIN_KEY_VALUE }}
      ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID || '' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Create hmac-key (wrangler)
        run: |
          set -e
          if [ -z "${{ env.STORE_ID }}" ]; then
            echo "STORE_ID empty; skipping"
            exit 0
          fi
          npx wrangler secrets-store secret create "${{ env.STORE_ID }}" --name hmac-key --scopes workers --value "${{ env.HMAC_KEY_VALUE }}" --remote || echo "maybe exists, continuing"

      - name: Create admin-key (wrangler)
        run: |
          set -e
          npx wrangler secrets-store secret create "${{ env.STORE_ID }}" --name admin-key --scopes workers --value "${{ env.ADMIN_KEY_VALUE }}" --remote || echo "maybe exists, continuing"

      - name: Fallback upsert via Cloudflare API (idempotent)
        if: always()
        run: |
          set -e
          if [ -z "${{ env.STORE_ID }}" ] || [ -z "${{ env.CF_API_TOKEN }}" ]; then
            echo "Missing STORE_ID or CF_API_TOKEN — skipping fallback"
            exit 0
          fi
          sudo apt-get update -y && sudo apt-get install -y jq
          create_or_replace_secret() {
            name="$1"; value="$2"
            body=$(jq -nc --arg n "$name" --arg v "$value" '[{name:$n, value:$v, scopes:["workers"], comment:"created by github action"}]')
            http_status=$(curl -s -o /tmp/resp.json -w "%{http_code}" \
              -X POST "https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/secrets_store/stores/${STORE_ID}/secrets" \
              -H "Authorization: Bearer ${CF_API_TOKEN}" \
              -H "Content-Type: application/json" \
              --data "$body" || true)
            if [ "$http_status" = "200" ] || [ "$http_status" = "201" ]; then
              echo "Created $name"
              return 0
            fi
            resp=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/secrets_store/stores/${STORE_ID}/secrets" -H "Authorization: Bearer ${CF_API_TOKEN}")
            secret_id=$(echo "$resp" | jq -r --arg NAME "$name" '.result[] | select(.name == $NAME) | .id' | head -n1)
            if [ -z "$secret_id" ] || [ "$secret_id" = "null" ]; then
              echo "Could not find existing secret id for $name; API response:"
              echo "$resp"
              return 1
            fi
            curl -s -X DELETE "https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/secrets_store/stores/${STORE_ID}/secrets/${secret_id}" -H "Authorization: Bearer ${CF_API_TOKEN}" || true
            http_status2=$(curl -s -o /tmp/resp2.json -w "%{http_code}" \
              -X POST "https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/secrets_store/stores/${STORE_ID}/secrets" \
              -H "Authorization: Bearer ${CF_API_TOKEN}" \
              -H "Content-Type: application/json" \
              --data "$body" || true)
            if [ "$http_status2" = "200" ] || [ "$http_status2" = "201" ]; then
              echo "Recreated $name"
              return 0
            fi
            echo "Failed to recreate $name"; cat /tmp/resp2.json || true
            return 1
          }
          create_or_replace_secret "hmac-key" "${HMAC_KEY_VALUE}" || true
          create_or_replace_secret "admin-key" "${ADMIN_KEY_VALUE}" || true

      - name: Publish Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: .
