name: Deploy Worker + ensure Secrets Store secrets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      STORE_ID: ${{ secrets.SECRETS_STORE_ID }}
      HMAC_KEY_VALUE: ${{ secrets.HMAC_KEY_VALUE }}
      ADMIN_KEY_VALUE: ${{ secrets.ADMIN_KEY_VALUE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Always reinstall wrangler fresh (avoid corrupted binary in CI cache)
      - name: Install wrangler fresh
        run: |
          rm -rf node_modules package-lock.json
          npm install --save-dev wrangler@latest
          ./node_modules/.bin/wrangler --version

      - name: Verify secrets presence
        run: |
          echo "STORE_ID present: ${STORE_ID:+yes}"
          echo "ACCOUNT_ID present: ${CLOUDFLARE_ACCOUNT_ID:+yes}"
          echo "API_TOKEN present: ${CLOUDFLARE_API_TOKEN:+yes}"
          echo "HMAC_KEY_VALUE present: ${HMAC_KEY_VALUE:+yes}"
          echo "ADMIN_KEY_VALUE present: ${ADMIN_KEY_VALUE:+yes}"

      # Create/update secrets via Secrets Store (non-fatal if already exists)
      - name: Ensure hmac-key
        run: |
          ./node_modules/.bin/wrangler secrets-store secret create "${STORE_ID}" \
            --name hmac-key --scopes workers --value "${HMAC_KEY_VALUE}" --remote || echo "exists, continuing"

      - name: Ensure admin-key
        run: |
          ./node_modules/.bin/wrangler secrets-store secret create "${STORE_ID}" \
            --name admin-key --scopes workers --value "${ADMIN_KEY_VALUE}" --remote || echo "exists, continuing"

      # Idempotent API fallback (create-or-replace) in case CLI create failed
      - name: Fallback upsert via Cloudflare API (idempotent)
        if: always()
        run: |
          set -eux
          if [ -z "${STORE_ID}" ] || [ -z "${CLOUDFLARE_API_TOKEN}" ] || [ -z "${CLOUDFLARE_ACCOUNT_ID}" ]; then
            echo "Skipping API fallback (missing STORE_ID, API_TOKEN or ACCOUNT_ID)"
            exit 0
          fi
          sudo apt-get update -y && sudo apt-get install -y jq
          upsert() {
            local name="$1" value="$2"
            local body
            body=$(jq -nc --arg n "$name" --arg v "$value" '[{name:$n, value:$v, scopes:["workers"], comment:"github action upsert"}]')
            # try create
            code=$(curl -s -o /tmp/create.json -w "%{http_code}" \
              -X POST "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/secrets_store/stores/${STORE_ID}/secrets" \
              -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" -H "Content-Type: application/json" --data "$body" || true)
            echo "create $name -> HTTP $code"
            [[ "$code" =~ ^(200|201)$ ]] && return 0
            # find id then replace
            list=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/secrets_store/stores/${STORE_ID}/secrets" \
              -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" -H "Content-Type: application/json")
            id=$(echo "$list" | jq -r --arg NAME "$name" '.result[] | select(.name==$NAME) | .id' | head -n1)
            [ -z "$id" ] || [ "$id" = "null" ] && { echo "No id for $name; skipping replace"; return 0; }
            curl -s -X DELETE "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/secrets_store/stores/${STORE_ID}/secrets/${id}" \
              -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" -H "Content-Type: application/json" || true
            code=$(curl -s -o /tmp/recreate.json -w "%{http_code}" \
              -X POST "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/secrets_store/stores/${STORE_ID}/secrets" \
              -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" -H "Content-Type: application/json" --data "$body" || true)
            echo "recreate $name -> HTTP $code"
          }
          upsert "hmac-key" "${HMAC_KEY_VALUE}" || true
          upsert "admin-key" "${ADMIN_KEY_VALUE}" || true

           - name: Publish Worker
        run: |
          set -euo pipefail
          echo "whoami (non-fatal):"
          ./node_modules/.bin/wrangler whoami || true
          echo "Deploying (debug logs)..."
          ./node_modules/.bin/wrangler deploy --log-level=debug
