name: Deploy Worker

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [preview, production]

    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      HMAC_KEY_VALUE: ${{ secrets.HMAC_KEY_VALUE }}
      ADMIN_KEY_VALUE: ${{ secrets.ADMIN_KEY_VALUE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Wrangler
        run: |
          npm install --no-audit --no-fund --save-dev wrangler@latest
          npx wrangler --version

      - name: Put Worker secrets (aci, ${{ matrix.env }})
        run: |
          set -euo pipefail
          printf "%s" "${HMAC_KEY_VALUE}"  | npx wrangler secret put SECRET --name aci --env ${{ matrix.env }}
          printf "%s" "${ADMIN_KEY_VALUE}" | npx wrangler secret put ADMIN_KEY --name aci --env ${{ matrix.env }}

      - name: Deploy (aci, ${{ matrix.env }})
        run: |
          set -euo pipefail
          npx wrangler deploy --name aci --env ${{ matrix.env }}
