name: Memory Schema & Placement Guard

on:
  pull_request:
    paths:
      - 'schemas/**'
      - 'entities/**'
      - 'tools/**'
      - '.github/workflows/memory-schema-guard.yml'
  push:
    branches:
      - main
    paths:
      - 'schemas/**'
      - 'entities/**'
      - 'tools/**'

jobs:
  validate-memory-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quick sanity checks
        run: |
          set -euo pipefail

          # 1) Ensure canonical schema exists
          if [ ! -f schemas/hivemind_memory.json ]; then
            echo "::error file=schemas/hivemind_memory.json::Missing canonical schema schemas/hivemind_memory.json"
            exit 1
          fi

          # 2) Reject AGI-specific schema files at repo root /schemas/
          if ls schemas 2>/dev/null | egrep -i 'agi' >/dev/null 2>&1; then
            echo "::error::AGI-specific schema files found under /schemas/. Move them to entities/agi/schemas/."
            ls -1 schemas | egrep -i 'agi' || true
            exit 1
          fi

          # 3) Reject banned flags/legacy patterns across repo (fast grep)
          if git grep -n --ignore-case -E 'codebox|--codebox|--weight|--slice:|--force|\\bhivemind export agi\\b|export_agi|hivemind_agi' >/dev/null 2>&1; then
            echo "::error::Found legacy export flags/calls. Search results:"
            git grep -n --ignore-case -E 'codebox|--codebox|--weight|--slice:|--force|\\bhivemind export agi\\b|export_agi|hivemind_agi' || true
            exit 1
          fi

          # 4) Reject top-level identity/entity fields in entities JSON artifacts
          BADFILES=$(git grep -n --line-number -E '"\b(identity|entity)\b"\s*:' -- 'entities' || true)
          if [ -n "$BADFILES" ]; then
            echo "::error::Found forbidden top-level 'identity' or 'entity' keys under entities/:"
            printf "%s\n" "$BADFILES"
            exit 1
          fi

          echo "All memory placement/schema guards passed."
